kind: Namespace
apiVersion: v1
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.24
    ports:
      - containerPort: 80
