apiVersion: v1
kind: Pod
metadata:
  name: nginx-lifecycle
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
  - name: nginx
    image: nginx:1.24
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "15"]
      # postStart:
      #   httpGet:
      #     port: 80
      #     path: /
    ports:
      - containerPort: 80