/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.shopping.list

import io.restassured.RestAssured
import org.junit.jupiter.api.BeforeEach
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.web.server.LocalServerPort
import org.springframework.test.context.ActiveProfiles
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertNotNull

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
internal class AppTest {

  @LocalServerPort
  var localPort: Int = 0

  @BeforeEach
  fun setUp() {
    RestAssured.port = localPort
  }

  @Test
  fun appHasAGreeting() {
    val items =
      RestAssured.get("/items")
      .then()
      .statusCode(200)
      .extract()
      .`as`(List::class.java)

    assertFalse { items.isEmpty() }
  }
}
