/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.shopping.list

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class App

fun main(args: Array<String>) {
  runApplication<App>(*args)
}
